#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
md_file_pattern="\.md-meta.xml"

exit_code=0

md_files=$(git status --short | grep -E "$md_file_pattern")

if [[ -n $md_files ]]
then
	echo 
	echo "\033[0;31mFound custom metadata files.\033[0m"
	echo "Please unstage the files commit again:"
	exit_code=1
fi

exit $exit_code